# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 34f39e353e620feb954385fbae3c10d4192857794848790208ef4d6310a878ef4b0708bea7dcee7a5567f6a767120768bd37292b2645802284f34f633ea8338f

test:
  secret_key_base: b6d745852d3e4e7ec4f2f98df36ef8824b8185b8f11be9e650fa816357eb3d9691b12a20a88dac5667170229bc482963116b5d5f689386b8ffa38807ad8ec88f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
